# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KWA_loc_ <- function(x, bw) {
    .Call(`_KWA1D_KWA_loc_`, x, bw)
}

KWA_scale_ <- function(x, df, bw_loc, bw_scale) {
    .Call(`_KWA1D_KWA_scale_`, x, df, bw_loc, bw_scale)
}

